### PR TITLE
renamed to twisted.py and made many small changes

### PR DESCRIPTION
**Pull request by fchapoton**
I have been through the file (renamed to `twisted.py`) and made many minor improvements. The doctests now pass. And the documentation is formatted correctly.

Note that using the down-to-earth binomial function is in principle much faster.

### CODE REVIEW

**Comment by pbelmans** [comment]
Thanks a lot!

Are you referring to the definition of `binom` in the function `twisted_hodge_number`? That is intentional, as per the documentation: we need that it evaluates to 0 for negative `n`.

**Comment by fchapoton** [comment]
no, your auxiliary function `binom` is ok. I am referring to the fact that the global `binomial` in sage is by default a complicated class/function able to take many kinds of arguments, and so slow. There is a specialised binomial function for integers in `arith.misc`.

**Comment by pbelmans** [comment]
Oh sure, that can be used. You already implemented that I think, so I guess all's good. Let me know if I'm missing something!

**Comment by fchapoton** [comment]
all's good here, I think. Please have a look at my pull-request at Hodge diamonds if you have time.

**Pull request merged**
